live_config_reload = true

import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[font.normal]
#family = "FiraCode Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[font.italic]
#family = "FiraCode Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Light Italic"

[font.bold]
#family = "FiraCode Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
#family = "FiraCode Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_padding = false
opacity = 1 
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 0
y = 0


